# Site settings
title:          "Chingo Club"
description:    "Launched! In this tactical board game, arm your soldiers with Rock, Paper or Scissors and enter fierce tactical combat! Get up the ranks, show off your tactical skills!"
url:            ""
image:          
  path: /assets/images/og-image.png

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:year/:month/:day/:title
paginate_path:  /page-:num/
paginate:       20

# Excludes
exclude: [ Gemfile, Gemfile.lock, components.gemspec ]
